### ISSUE TITLE
Circular dependency issue

### ISSUE THREAD

**Issue by kobbled** [gavanderhoorn/rossum#28]
This is about the issue of circular dependencies using onerobotics kUnit and Strings. I have put together the packages I am using in https://github.com/kobbled/rossum-test.

**Comment by kobbled** [comment]
This is my output using a build folder at the top level of this project:

```
> rossum ../ -v
INFO     | This is rossum v0.1.7
DEBUG    | Checking: c:\Users\matt\Dropbox\Programming\Git\rossum-test\KUnit\build\robot.ini
C:\Users\matt\Dropbox\Programming\Fanuc\rossum-0.1.4-distrib\\rossum.py:267: DeprecationWarning: The 'warn' method is
deprecated, use 'warning' instead
  "source space".format(ROBOT_INI_NAME))
WARNING  | No robot.ini in CWD, and no alternative provided, trying source space
DEBUG    | Checking: c:\Users\matt\Dropbox\Programming\Git\rossum-test\KUnit\src\robot.ini
INFO     | Found robot.ini in source space
C:\Users\matt\Dropbox\Programming\Fanuc\rossum-0.1.4-distrib\\rossum.py:286: DeprecationWarning: The 'warn' method is
deprecated, use 'warning' instead
  "settings!".format(ROBOT_INI_NAME))
WARNING  | Found robot.ini contains potentially conflicting ktrans settings!
INFO     | Found Roboguide version: V9.1098 (Rev.F)
DEBUG    | Most likely FANUC base-dir: C:\Program Files (x86)\FANUC
INFO     | Using C:\Program Files (x86)\FANUC as FANUC software base directory
DEBUG    | Trying to auto-detect ktrans location ..
DEBUG    | Looking in C:\Program Files (x86)\FANUC\WinOLPC\bin ..
DEBUG    | Found ktrans.exe in C:\Program Files (x86)\FANUC\WinOLPC\bin
INFO     | ktrans location: C:\Program Files (x86)\FANUC\WinOLPC\bin\ktrans.exe
INFO     | Setting default system core version to: V9.10-1
DEBUG    | Trying to find support dir for core version: V9.10-1
DEBUG    | Looking in C:\Program Files (x86)\FANUC\WinOLPC\Versions\V910-1\support ..
DEBUG    | Found V9.10-1 support dir: C:\Program Files (x86)\FANUC\WinOLPC\Versions\V910-1\support
INFO     | Karel core support dir: C:\Program Files (x86)\FANUC\WinOLPC\Versions\V910-1\support
INFO     | ktransw location: ktransw.cmd
DEBUG    | Using build file template: C:\Users\matt\Dropbox\Programming\Fanuc\rossum-0.1.4-distrib\build.ninja.em
INFO     | Source space(s) searched for packages (in order: src, args):
INFO     |   c:\Users\matt\Dropbox\Programming\Git\rossum-test\KUnit\src
INFO     |   c:\Users\matt\Dropbox\Programming\Git\rossum-test
DEBUG    | Searching in c:\Users\matt\Dropbox\Programming\Git\rossum-test\KUnit\src
DEBUG    |   found 1 manifest(s)
DEBUG    | Searching in c:\Users\matt\Dropbox\Programming\Git\rossum-test
DEBUG    |   found 4 manifest(s)
DEBUG    | Found 5 manifest(s) total
DEBUG    | Loaded package.json from c:\Users\matt\Dropbox\Programming\Git\rossum-test\KUnit\src
DEBUG    | Loaded package.json from c:\Users\matt\Dropbox\Programming\Git\rossum-test\errors\src
DEBUG    | Loaded package.json from c:\Users\matt\Dropbox\Programming\Git\rossum-test\Hash\src
DEBUG    | Loaded package.json from c:\Users\matt\Dropbox\Programming\Git\rossum-test\KUnit\src
DEBUG    | Loaded package.json from c:\Users\matt\Dropbox\Programming\Git\rossum-test\Strings\src
INFO     | Found 5 package(s) in source space(s):
INFO     |   KUnit (v1.0.0)
INFO     |   errors (v0.0.1)
INFO     |   Hash (v0.0.1)
INFO     |   KUnit (v1.0.0)
INFO     |   Strings (v0.0.1)
DEBUG    | Checking dependencies for: KUnit, errors, Hash, KUnit, Strings
DEBUG    |   KUnit - deps: Strings
DEBUG    |     satisfied
DEBUG    |   errors - deps: none
DEBUG    |     satisfied
DEBUG    |   Hash - deps: KUnit, Strings
DEBUG    |     satisfied
DEBUG    |   KUnit - deps: Strings
DEBUG    |     satisfied
DEBUG    |   Strings - deps: KUnit, errors
DEBUG    |     satisfied
DEBUG    | Resolving dependencies for: KUnit, errors, Hash, KUnit, Strings
DEBUG    |   KUnit
DEBUG    |     Strings: found
DEBUG    |   errors
DEBUG    |   Hash
DEBUG    |     KUnit: found
DEBUG    |     Strings: found
DEBUG    |   KUnit
DEBUG    |     Strings: found
DEBUG    |   Strings
DEBUG    |     KUnit: found
DEBUG    |     errors: found
DEBUG    | Resolving includes for: KUnit, errors, Hash, KUnit, Strings
DEBUG    |   KUnit
Traceback (most recent call last):
  File "C:\Users\matt\Dropbox\Programming\Fanuc\rossum-0.1.4-distrib\\rossum.py", line 783, in <module>
    main()
  File "C:\Users\matt\Dropbox\Programming\Fanuc\rossum-0.1.4-distrib\\rossum.py", line 437, in main
    resolve_includes(all_pkgs)
  File "C:\Users\matt\Dropbox\Programming\Fanuc\rossum-0.1.4-distrib\\rossum.py", line 662, in resolve_includes
    inc_dirs = dedup(resolve_includes_for_pkg(pkg))
  File "C:\Users\matt\Dropbox\Programming\Fanuc\rossum-0.1.4-distrib\\rossum.py", line 678, in resolve_includes_for_pkg
    inc_dirs.extend(resolve_includes_for_pkg(dep_pkg))
  File "C:\Users\matt\Dropbox\Programming\Fanuc\rossum-0.1.4-distrib\\rossum.py", line 678, in resolve_includes_for_pkg
    inc_dirs.extend(resolve_includes_for_pkg(dep_pkg))
  File "C:\Users\matt\Dropbox\Programming\Fanuc\rossum-0.1.4-distrib\\rossum.py", line 678, in resolve_includes_for_pkg
    inc_dirs.extend(resolve_includes_for_pkg(dep_pkg))
  [Previous line repeated 990 more times]
  File "C:\Users\matt\Dropbox\Programming\Fanuc\rossum-0.1.4-distrib\\rossum.py", line 674, in resolve_includes_for_pkg
    abs_inc = os.path.abspath(os.path.join(pkg.location, inc_dir))
  File "C:\Users\matt\AppData\Local\Programs\Python\Python37-32\lib\ntpath.py", line 526, in abspath
    return normpath(_getfullpathname(path))
  File "C:\Users\matt\AppData\Local\Programs\Python\Python37-32\lib\ntpath.py", line 472, in normpath
    prefix, path = splitdrive(path)
  File "C:\Users\matt\AppData\Local\Programs\Python\Python37-32\lib\ntpath.py", line 141, in splitdrive
    p = os.fspath(p)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by kobbled** [comment]
Changed to PR #31

**Comment by gavanderhoorn** [comment]
#31 was merged, so closing this one.

Thanks again @kobbled for your contributions.
